disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - modifier_order
  - toggle_bool
  - unowned_variable_capture
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

included:
  - DicomPreview
  - DicomPreviewExtension

excluded:
  - Pods
  - .build
  - build
  - DerivedData

line_length:
  warning: 160
  error: 160

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 600
  error: 1000

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - URL
    - x
    - y
  allowed_symbols: ["_"]

cyclomatic_complexity:
  warning: 15
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3

reporter: "xcode" 